mixed-port: 7890
allow-lan: false
mode: rule
log-level: silent
external-controller: 10.11.11.10:9090

dns:
    enable: true # set true to enable dns (default is false)
    ipv6: true  # default is false
    listen: 0.0.0.0:1053
    enhanced-mode: redir-host
nameserver:
    - 8.8.8.8
proxies:
  - {name: FRA ğŸ‡«ğŸ‡· Gravelines, server: 95.85.90.181, port: 803, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: FRA ğŸ‡«ğŸ‡· Paris, server: 135.125.248.215, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: FRA ğŸ‡«ğŸ‡· Paris 2, server: 141.95.0.26, port: 826, type: ss, cipher: chacha20-ietf-poly1305, password: sF43Xt2gONqcgFX563, udp: true}
  - {name: FRA ğŸ‡«ğŸ‡· Roubaix, server: 95.85.90.181, port: 803, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: FRA ğŸ‡«ğŸ‡· Roubaix 2, server: 95.85.90.181, port: 807, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: FRA ğŸ‡«ğŸ‡· Roubaix 3, server: 95.85.90.181, port: 808, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: FRA ğŸ‡«ğŸ‡· Roubaix 4, server: 95.85.90.181, port: 810, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: FRA ğŸ‡«ğŸ‡· Roubaix 5, server: 151.80.27.161, port: 2376, type: ss, cipher: aes-256-gcm, password: faBAoD54k87UJG7, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf, server: 146.0.36.44, port: 6679, type: ss, cipher: aes-256-gcm, password: TEzjfAYq2IjtuoS, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 2, server: 161.97.131.160, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 3, server: 178.18.255.190, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 4, server: 194.163.134.104, port: 443, type: ss, cipher: chacha20-ietf-poly1305, password: dZpagSuA9Vxe, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª Hesse, server: 135.125.236.229, port: 50003, type: ss, cipher: aes-256-cfb, password: !<str> 8460400130, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª Hesse 2, server: 135.125.244.103, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª Hesse 3, server: 135.125.248.215, port: 800, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª Hesse 4, server: 141.95.0.23, port: 800, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª Nuremberg, server: 95.111.255.56, port: 443, type: ss, cipher: chacha20-ietf-poly1305, password: Wh9NryUjBiKu, udp: true}
  - {name: GER ğŸ‡©ğŸ‡ª Nuremberg 2, server: 213.136.80.36, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: "ufo Germany ğŸ‡©ğŸ‡ª Berlin", server: 196.244.72.5, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: "ufo Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf 2", server: 85.114.138.92, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: "ufo Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf", server: 93.186.201.124, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain 3", server: 18.185.63.41, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain 2", server: 185.104.184.78, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain", server: 3.126.91.132, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: "ufo Germany ğŸ‡©ğŸ‡ª LimburganderLahn 2", server: 135.125.248.209, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: "ufo Germany ğŸ‡©ğŸ‡ª LimburganderLahn", server: 135.125.253.250, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: "Aloha Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf", server: 178.18.255.190, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3}
  - {name: "Aloha Germany ğŸ‡©ğŸ‡ª Limburg an der Lahn", server: 135.125.244.103, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3}
  - {name: "Aloha Germany ğŸ‡©ğŸ‡ª Nuremberg", server: 213.136.80.36, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3}
  - {name: LUX ğŸ‡±ğŸ‡º Luxembourg, server: 172.255.248.35, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: MDA ğŸ‡²ğŸ‡© Chisinau, server: 192.121.87.89, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: MEX ğŸ‡²ğŸ‡½ Mexico City, server: 169.57.35.97, port: 8389, type: ss, cipher: chacha20-ietf-poly1305, password: 3Q5yYEGGMu8jU2p25aWL, udp: true}
  - {name: MKD ğŸ‡²ğŸ‡° Skopje, server: 46.183.185.15, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: MLT ğŸ‡²ğŸ‡¹ Qormi, server: 185.89.238.36, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: MLT ğŸ‡²ğŸ‡¹ Safi, server: 185.89.238.36, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: PRT ğŸ‡µğŸ‡¹ Lisbon, server: 185.90.57.152, port: 8388, type: ss, cipher: chacha20-ietf-poly1305, password: qSnstpCypymLvPeyLRqf, udp: true}
  - {name: ROM ğŸ‡·ğŸ‡´ Bucharest, server: 86.105.25.162, port: 8388, type: ss, cipher: chacha20-ietf-poly1305, password: gKDDFZyBmBH5Ru46xBAK, udp: true}
  - {name: ROM ğŸ‡·ğŸ‡´ Bucharest 2, server: 194.68.44.206, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: ROM ğŸ‡·ğŸ‡´ Lasi, server: 185.225.19.64, port: 50003, type: ss, cipher: aes-256-cfb, password: !<str> 8460400130, udp: true}
  - {name: RUS ğŸ‡·ğŸ‡º Moscow, server: 83.217.9.76, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: RUS ğŸ‡·ğŸ‡º Moscow 2, server: 185.4.65.6, port: 21247, type: ss, cipher: aes-256-cfb, password: vDS9G2p, udp: true}
  - {name: SWIT ğŸ‡¨ğŸ‡­ Zurich, server: 212.237.210.158, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: TUR ğŸ‡¹ğŸ‡· BahÃ§elievler, server: 185.17.113.234, port: 812, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: TUR ğŸ‡¹ğŸ‡· Istanbul, server: 141.98.119.156, port: 50003, type: ss, cipher: aes-256-cfb, password: !<str> 8460400130, udp: true}
  - {name: TUR ğŸ‡¹ğŸ‡· Istanbul 2, server: 141.98.119.180, port: 50003, type: ss, cipher: aes-256-cfb, password: !<str> 8460400130, udp: true}
  - {name: TUR ğŸ‡¹ğŸ‡· Istanbul 3, server: 185.17.113.234, port: 806, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, udp: true}
  - {name: TUR ğŸ‡¹ğŸ‡· Istanbul 4, server: 185.219.134.52, port: 50003, type: ss, cipher: aes-256-cfb, password: !<str> 8460400130, udp: true}
  - {name: TUR ğŸ‡¹ğŸ‡· Istanbul 5, server: 185.219.134.182, port: 50003, type: ss, cipher: aes-256-cfb, password: !<str> 8460400130, udp: true}
  - {name: "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 1", server: 141.98.119.180, port: 50003, type: ss, cipher: aes-256-cfb, password: "8460400130"}
  - {name: "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 2", server: 185.219.134.52, port: 50003, type: ss, cipher: aes-256-cfb, password: "8460400130"}
  - {name: "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 3", server: 185.219.133.176, port: 50003, type: ss, cipher: aes-256-cfb, password: "8460400130"}
  - {name: "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 4", server: 185.219.134.182, port: 50003, type: ss, cipher: aes-256-cfb, password: "8460400130"}
  - {name: "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 5", server: 141.98.119.156, port: 50003, type: ss, cipher: aes-256-cfb, password: "8460400130"}
  - {name: "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 6", server: 185.219.134.161, port: 50003, type: ss, cipher: aes-256-cfb, password: "8460400130"}
  - {name: UKR ğŸ‡ºğŸ‡¦ Kharkiv, server: 195.211.41.10, port: 989, type: ss, cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, udp: true}
  - {name: UKR ğŸ‡ºğŸ‡¦ Kyiv, server: 37.19.218.197, port: 8388, type: ss, cipher: chacha20-ietf-poly1305, password: Mx6DztQqZb7j34FdWjER, udp: true}

proxy-providers:
  au:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=AU"
    path: sspool.herokuapp.com/provider-au.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  cn:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=CN,HK,TW"
    path: sspool.herokuapp.com/provider-cn.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  us:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=US"
    path: sspool.herokuapp.com/provider-us.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ca:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=CA"
    path: sspool.herokuapp.com/provider-ca.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  jp:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=JP"
    path: sspool.herokuapp.com/provider-jp.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  sg:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=SG"
    path: sspool.herokuapp.com/provider-sg.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ru:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=RU"
    path: sspool.herokuapp.com/provider-ru.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ch:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=CH"
    path: sspool.herokuapp.com/provider-ch.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  de:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=DE"
    path: sspool.herokuapp.com/provider-de.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  fr:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=FR"
    path: sspool.herokuapp.com/provider-fr.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  gb:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=GB"
    path: sspool.herokuapp.com/provider-gb.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  nl:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=NL"
    path: sspool.herokuapp.com/provider-nl.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  others:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?nc=CN,HK,TW,US,CA,JP,SG,AU,CH,DE,GB,NL,FR,RU"
    path: sspool.herokuapp.com/provider-others.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  all:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies"
    path: sspool.herokuapp.com/provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
      
proxy-groups:
  - name: ğŸ”° All Proxies
    type: select
    proxies:
      - ğŸ”¥ Auto(Best ping)
      - FRA ğŸ‡«ğŸ‡· Gravelines
      - FRA ğŸ‡«ğŸ‡· Paris
      - FRA ğŸ‡«ğŸ‡· Paris 2
      - FRA ğŸ‡«ğŸ‡· Roubaix
      - FRA ğŸ‡«ğŸ‡· Roubaix 2
      - FRA ğŸ‡«ğŸ‡· Roubaix 3
      - FRA ğŸ‡«ğŸ‡· Roubaix 4
      - FRA ğŸ‡«ğŸ‡· Roubaix 5
      - GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf
      - GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 2
      - GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 3
      - GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 4
      - GER ğŸ‡©ğŸ‡ª Hesse
      - GER ğŸ‡©ğŸ‡ª Hesse 2
      - GER ğŸ‡©ğŸ‡ª Hesse 3
      - GER ğŸ‡©ğŸ‡ª Hesse 4
      - GER ğŸ‡©ğŸ‡ª Nuremberg
      - "ufo Germany ğŸ‡©ğŸ‡ª Berlin"
      - "ufo Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf 2"
      - "ufo Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf"
      - "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain 3"
      - "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain 2"
      - "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain"
      - "ufo Germany ğŸ‡©ğŸ‡ª LimburganderLahn 2"
      - "Aloha Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf"
      - "Aloha Germany ğŸ‡©ğŸ‡ª Limburg an der Lahn"
      - "Aloha Germany ğŸ‡©ğŸ‡ª Nuremberg"
      - "ufo Germany ğŸ‡©ğŸ‡ª LimburganderLahn"
      - GER ğŸ‡©ğŸ‡ª Nuremberg 2
      - LUX ğŸ‡±ğŸ‡º Luxembourg
      - MDA ğŸ‡²ğŸ‡© Chisinau
      - MEX ğŸ‡²ğŸ‡½ Mexico City
      - MKD ğŸ‡²ğŸ‡° Skopje
      - MLT ğŸ‡²ğŸ‡¹ Qormi
      - MLT ğŸ‡²ğŸ‡¹ Safi
      - PRT ğŸ‡µğŸ‡¹ Lisbon
      - ROM ğŸ‡·ğŸ‡´ Bucharest
      - ROM ğŸ‡·ğŸ‡´ Bucharest 2
      - ROM ğŸ‡·ğŸ‡´ Lasi
      - RUS ğŸ‡·ğŸ‡º Moscow
      - RUS ğŸ‡·ğŸ‡º Moscow 2
      - SWIT ğŸ‡¨ğŸ‡­ Zurich
      - TUR ğŸ‡¹ğŸ‡· BahÃ§elievler
      - TUR ğŸ‡¹ğŸ‡· Istanbul
      - TUR ğŸ‡¹ğŸ‡· Istanbul 2
      - TUR ğŸ‡¹ğŸ‡· Istanbul 3
      - TUR ğŸ‡¹ğŸ‡· Istanbul 4
      - TUR ğŸ‡¹ğŸ‡· Istanbul 5
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 1"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 2"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 3"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 4"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 5"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 6"
      - UKR ğŸ‡ºğŸ‡¦ Kharkiv
      - UKR ğŸ‡ºğŸ‡¦ Kyiv

  - name: ğŸ”¥ Auto(Best ping)
    type: url-test
    url: http://connectivitycheck.gstatic.com/generate_204
    interval: 600
    proxies:
      - FRA ğŸ‡«ğŸ‡· Gravelines
      - FRA ğŸ‡«ğŸ‡· Paris
      - FRA ğŸ‡«ğŸ‡· Paris 2
      - FRA ğŸ‡«ğŸ‡· Roubaix
      - FRA ğŸ‡«ğŸ‡· Roubaix 2
      - FRA ğŸ‡«ğŸ‡· Roubaix 3
      - FRA ğŸ‡«ğŸ‡· Roubaix 4
      - FRA ğŸ‡«ğŸ‡· Roubaix 5
      - GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf
      - GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 2
      - GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 3
      - GER ğŸ‡©ğŸ‡ª DÃ¼sseldorf 4
      - GER ğŸ‡©ğŸ‡ª Hesse
      - GER ğŸ‡©ğŸ‡ª Hesse 2
      - GER ğŸ‡©ğŸ‡ª Hesse 3
      - GER ğŸ‡©ğŸ‡ª Hesse 4
      - GER ğŸ‡©ğŸ‡ª Nuremberg
      - GER ğŸ‡©ğŸ‡ª Nuremberg 2
      - "ufo Germany ğŸ‡©ğŸ‡ª Berlin"
      - "ufo Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf 2"
      - "ufo Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf"
      - "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain 3"
      - "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain 2"
      - "ufo Germany ğŸ‡©ğŸ‡ª FrankfurtamMain"
      - "ufo Germany ğŸ‡©ğŸ‡ª LimburganderLahn 2"
      - "ufo Germany ğŸ‡©ğŸ‡ª LimburganderLahn"
      - "Aloha Germany ğŸ‡©ğŸ‡ª DÃ¼sseldorf"
      - "Aloha Germany ğŸ‡©ğŸ‡ª Limburg an der Lahn"
      - "Aloha Germany ğŸ‡©ğŸ‡ª Nuremberg"
      - LUX ğŸ‡±ğŸ‡º Luxembourg
      - MDA ğŸ‡²ğŸ‡© Chisinau
      - MEX ğŸ‡²ğŸ‡½ Mexico City
      - MKD ğŸ‡²ğŸ‡° Skopje
      - MLT ğŸ‡²ğŸ‡¹ Qormi
      - MLT ğŸ‡²ğŸ‡¹ Safi
      - PRT ğŸ‡µğŸ‡¹ Lisbon
      - ROM ğŸ‡·ğŸ‡´ Bucharest
      - ROM ğŸ‡·ğŸ‡´ Bucharest 2
      - ROM ğŸ‡·ğŸ‡´ Lasi
      - RUS ğŸ‡·ğŸ‡º Moscow
      - RUS ğŸ‡·ğŸ‡º Moscow 2
      - SWIT ğŸ‡¨ğŸ‡­ Zurich
      - TUR ğŸ‡¹ğŸ‡· BahÃ§elievler
      - TUR ğŸ‡¹ğŸ‡· Istanbul
      - TUR ğŸ‡¹ğŸ‡· Istanbul 2
      - TUR ğŸ‡¹ğŸ‡· Istanbul 3
      - TUR ğŸ‡¹ğŸ‡· Istanbul 4
      - TUR ğŸ‡¹ğŸ‡· Istanbul 5
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 1"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 2"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 3"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 4"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 5"
      - "Speedy Quark Turkey ğŸ‡¹ğŸ‡· Istanbul 6"
      - UKR ğŸ‡ºğŸ‡¦ Kharkiv
      - UKR ğŸ‡ºğŸ‡¦ Kyiv

  - name: â›”Direct
    type: select
    proxies:
      - DIRECT
rule-sets:
  - name: lhie # åç§°
    type: url  # ç±»æ–° ç›®å‰ä»…æ”¯æŒ url
    url: 'https://raw.githubusercontent.com/lhie1/Rules/master/Clash/Rule.yml'
    target-map:             # ç”¨äºæ›¿æ¢ å•æ¡è§„åˆ™ çš„ ç›®æ ‡ä»£ç†ç»„ ä¸éœ€è¦è¯·æŠŠè¯¥è¡Œä¸€èµ·åˆ é™¤ï¼Œå‹¿ç•™ç©ºåˆ—è¡¨
      - 'AdBlock,REJECT'
      - 'Media,PROXY'
      - 'GlobalTV,PROXY'
      - 'AsianTV,PROXY'
      - 'Domestic,PROXY'
      - 'Proxy,PROXY'
    rule-skip:              # è·³è¿‡éƒ¨åˆ†åŒ¹é… è§„åˆ™  ä¸éœ€è¦è¯·æŠŠè¯¥è¡Œä¸€èµ·åˆ é™¤ï¼Œå‹¿ç•™ç©ºåˆ—è¡¨
      - 'MATCH'
    target-skip:            # è·³è¿‡éƒ¨åˆ†ç›®æ ‡ä»£ç†ç»„ ä¸éœ€è¦è¯·æŠŠè¯¥è¡Œä¸€èµ·åˆ é™¤ï¼Œå‹¿ç•™ç©ºåˆ—è¡¨
      - 'Final'
      - 'Others'

rules:
  - MATCH ,ğŸ”° All Proxies,ğŸ”¥ Auto(Best ping)
